name: CreateSObject_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Salesforce.CreateSObject/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Salesforce.CreateSObject
      env_var_name_1: Salesforce_Client_Secret
      env_var_name_2: Salesforce_Password
      env_var_name_3: Salesforce_Security_Token
      env_var_name_4: Salesforce_ClientID
      env_var_name_5: Salesforce_Username
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
      env_var_value_2: ${{ secrets.SALESFORCE_PASSWORD }}
      env_var_value_3: ${{ secrets.SALESFORCE_SECURITY_TOKEN }}
      env_var_value_4: ${{ secrets.SALESFORCE_CLIENTID }}
      env_var_value_5: ${{ secrets.SALESFORCE_USERNAME }}
