name: PubSubPublish_test_on_push
permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Salesforce.PubSubPublish/**'
      - '.github/workflows/PubSubPublish*'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@testsettings
    with:
      workdir: Frends.Salesforce.PubSubPublish
      dotnet_version: 8.0.x
      strict_analyzers: true
      env_var_name_1: SALESFORCE_PUBSUB_API_URL
      env_var_name_2: SALESFORCE_INSTANCE_URL
      env_var_name_3: SALESFORCE_TENANT_ID
      env_var_name_4: SALESFORCE_CLIENT_ID
      env_var_name_5: SALESFORCE_CLIENT_SECRET
      env_var_name_6: SALESFORCE_USERNAME
      env_var_name_7: SALESFORCE_PASSWORD
      env_var_name_8: SALESFORCE_SECURITY_TOKEN
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.SALESFORCE_PUBSUB_API_URL }}
      env_var_value_2: ${{ secrets.SALESFORCE_DOMAIN_URL }}
      env_var_value_3: ${{ secrets.SALESFORCE_TENANT_ID }}
      env_var_value_4: ${{ secrets.SALESFORCE_CLIENTID }}
      env_var_value_5: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
      env_var_value_6: ${{ secrets.SALESFORCE_USERNAME }}
      env_var_value_7: ${{ secrets.SALESFORCE_PASSWORD }}
      env_var_value_8: ${{ secrets.SALESFORCE_SECURITY_TOKEN }}
